name: Java CI with Gradle

on:
  push:
    branches: [ main ]  # 변경사항이 main 브랜치에 푸시될 때 실행
  pull_request:
    branches: [ main ]  # 풀 리퀘스트가 main 브랜치에 올라올 때 실행

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
        
      - name: Test with Gradle
        run: ./gradlew test --console=plain

  boot-jar:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
        
      - name: Build JAR with Gradle Wrapper
        run: ./gradlew bootJar
        
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: build/libs/*.jar
