name: Docker Image Delivery

on:
  push:
    branches: [ CICD ]
  pull_request:
    branches: [ CICD ]

jobs:
  # 빌드가 완료되면 도커 이미지 생성 후 도커 허브에 저장
  deliver:
    needs: boot-jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Image Tag
        id: image-tag
        run: echo "TAG=$(date +%s)-ci" >> "$GITHUB_OUTPUT"

      - name: Build the Docker image
        env:
          TAG: ${{ steps.image-tag.outputs.TAG }}
        run: docker build . --file Dockerfile --tag "${{ secrets.DOCKERHUB_USERNAME }}/todo-boot:$TAG"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Docker Image
        env:
          TAG: ${{ steps.image-tag.outputs.TAG }}
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/todo-boot:$TAG"
